#=========================================================================#
#USER
#=========================================================================#
###
# get usuario
GET http://localhost:8000/api/users

###
#GET usuario by email
GET http://localhost:8000/api/users/email/isadora3@example.com

###
# Get usuario by code
GET http://localhost:8000/api/users/code/d368f6d4-eace-41e0-bffc-83d45fba52ae

###
# Delete usuario by code
DELETE  http://localhost:8000/api/users/delete/d368f6d4-eace-41e0-bffc-83d45fba52ae

###
# Update usuario by code
PUT  http://localhost:8000/api/users/update/7fdb8e4b-803b-432c-b601-4c4a5357bdb7

{
        "email": "ozair3@example.com"
}

###
# Cadastro de usuario
POST http://localhost:8000/api/users

  {
        "name": "Nicolle",
        "email": "nicolle@example.com",
        "password": "123456",
        "is_active": true,
        "is_admin": false
  }


#=========================================================================#
#PRODUCT
#=========================================================================#

###
# get de produtos
GET http://localhost:8000/api/products

###
# busca de produtos by code
GET http://localhost:8000/api/products/code/3cfad7d5-e7a4-482f-9917-f5cb661086ee


###
# busca de produtos by name
GET http://localhost:8000/api/products/name/Caneta Bic

###
# busca de produtos by category
GET http://localhost:8000/api/products/category/escrita
###
# busca de produtos by sku
 GET http://localhost:8000/api/products/sku/13555

###
# Cadastro de produtos
POST http://localhost:8000/api/products

{
  "name": "Caneta Bic",
  "description": "Caneta Azul",
  "price": 1.50,
  "units_in_stock": 10,
  "image": "url_caneta",
  "category": "escrita",
  "sku": "1355"
}

###
# Atualizacao de produtos pelo codigo
PUT http://localhost:8000/api/products/update/code/3cfad7d5-e7a4-482f-9917-f5cb661086ee

{
    "price" : 2
}

###
# delete produtos by sku
DELETE  http://localhost:8000/api/products/remove/code/d7e316cc-628d-4c83-b1c4-da5bf1f8221d

#=========================================================================#
#ADDRESS
#=========================================================================#


###
# Get endereco por email
GET http://localhost:8000/api/address/email/nicolle@example.com


###
# Cadastro de endereco
POST http://localhost:8000/api/address

{
  "user": {
    "user_code": "14814bf3-0e52-4999-ac12-d0da36bf2610",
    "email":"nicolle@example.com"
  },
   "address": {
    "street": "Rua Canasviais",
    "number": 200,
    "zip_code": "54321-000",
    "district": "Bairro dos Limoeiros",
    "city": "Sao Paulo",
    "state": "SP",
    "is_delivery": false

  }
}

#=========================================================================#
#CART
#=========================================================================#
###
# Cadastro de Cart
POST http://localhost:8000/api/cart

  {
    "user": {
        "user_code": "14814bf3-0e52-4999-ac12-d0da36bf2610",
        "email":"nicolle@example.com"
    },
    "order_item":{
          "product": {
                "name": "Caneta Bic",
                "description": "Caneta Amarela",
                "price": 1.5,
                "units_in_stock": 10,
                "image": "url_caneta",
                "category": "escrita",
                "sku": "135587"
              } ,
          "quantity": 1
        }

  }

###
# deletar carrinho
DELETE  http://localhost:8000/api/cart/2e0f13e5-3de7-410f-aa36-4a8ec6801cf2

###
# deletar produto do carrinho
DELETE  http://localhost:8000/api/cart/delete/product

{
  "user": {
        "user_code": "14814bf3-0e52-4999-ac12-d0da36bf2610",
        "email":"nicolle@example.com"
    },
  "product_sku": "13555"
}

###
# deletar produto do carrinho
PUT  http://localhost:8000/api/cart/update

{
  "user": {
        "user_code": "14814bf3-0e52-4999-ac12-d0da36bf2610",
        "email":"nicolle@example.com"
    },
  "product_sku": "135587",
  "quantity" : 2
}

#=========================================================================#
#ORDER_ITEM
#=========================================================================#
###
# Fechar uma ordem
POST http://localhost:8000/api/order

{
  "user": {
    "code": "14814bf3-0e52-4999-ac12-d0da36bf2610"
  },
  "address":{
          "address":{
          "street": "Rua Canasviais",
          "number": 200,
          "zip_code": "54321-000",
          "district": "Bairro dos Limoeiros",
          "city": "Sao Paulo",
          "state": "SP",
          "is_delivery": false
    }
  },

  "order": {

  }
}